#!/usr/bin/env python3
"""
Initialize 3x-ui node databases and generate docker-compose.local.yml for the
local dev stack.  Reads data.local.json (project root) as the single source of
truth for node configuration.

Operations (always run together):
  1. Generate local/docker-compose.local.yml from data.local.json.
     The file is git-ignored and must not be edited by hand.
  2. Ensure each node's database exists and is patched:
       - sets apiToken, webPort, webBasePath from data.local.json
       - clears HTTPS settings so the panel runs on plain HTTP

DB behaviour when a database is missing:
  default      look for local/nodes/<host>/db/backup.db and copy it;
               if absent, start the node container briefly so 3x-ui creates the
               schema, then stop and patch
  --restore    same seed logic but also overwrites an existing x-ui.db
               (idempotent re-seed from backup.db)
  --patch-only skip all DB creation; exit with error if any DB is missing

To seed a node from a backup, place the source file at:
  local/nodes/<host>/db/backup.db   (git-ignored)

TLS certificates (optional, for xray inbounds that need TLS):
  local/nodes/<host>/certs/         (git-ignored, mounted to /root/cert)

Image tag: set XUI_IMAGE_TAG in .env.local (global, default v3.2.0).

Run from the project root (Makefile handles this automatically).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOCAL_DIR = PROJECT_ROOT / "local"
DATA_FILE = PROJECT_ROOT / "data.local.json"
ENV_FILE = PROJECT_ROOT / ".env.local"
COMPOSE_OUT = LOCAL_DIR / "docker-compose.local.yml"
DEFAULT_IMAGE = "ghcr.io/mhsanaei/3x-ui"
DEFAULT_TAG = "v3.2.0"


# ── helpers ───────────────────────────────────────────────────────────────────


def load_env_file(path: Path) -> None:
    """Merge key=value pairs from path into os.environ (existing vars win)."""
    if not path.exists():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        os.environ.setdefault(key.strip(), val.strip().strip('"').strip("'"))


def load_nodes() -> list[dict]:
    if not DATA_FILE.exists():
        print(f"[error] {DATA_FILE} not found.")
        print("  cp local/data.local.json.sample data.local.json")
        print("  # fill in host, port, basePath, apiToken for each node")
        sys.exit(1)
    nodes = json.loads(DATA_FILE.read_text(encoding="utf-8")).get("nodes", [])
    if not nodes:
        print("[warn] data.local.json has no nodes.")
    return nodes


def node_dir(node: dict) -> Path:
    return LOCAL_DIR / "nodes" / node["host"]


def db_dir(node: dict) -> Path:
    return node_dir(node) / "db"


def db_path(node: dict) -> Path:
    return db_dir(node) / "x-ui.db"


def backup_db_path(node: dict) -> Path:
    return db_dir(node) / "backup.db"


def certs_dir(node: dict) -> Path:
    return node_dir(node) / "certs"


def _drop_wal(db: Path) -> None:
    for f in (db.with_name("x-ui.db-wal"), db.with_name("x-ui.db-shm")):
        f.unlink(missing_ok=True)


# ── compose generation ────────────────────────────────────────────────────────


def _q(s: str) -> str:
    """Wrap in double quotes, escape inner double quotes."""
    return '"' + s.replace('"', '\\"') + '"'


def is_local_node(node: dict) -> bool:
    """True for nodes that run as local Docker containers (simple hostname, no dots)."""
    return "." not in node["host"]


def generate_compose(nodes: list[dict]) -> None:
    """Write docker-compose.local.yml from data.local.json (absolute paths).

    Only nodes with a simple hostname (no dots) become Docker services.
    Nodes with real FQDNs (dots) are treated as external and skipped.
    """
    tag = os.environ.get("XUI_IMAGE_TAG", DEFAULT_TAG)
    http_port = int(os.environ.get("VPN_HOST_HTTP_PORT", "8080"))
    env_file = str(ENV_FILE)
    root = str(PROJECT_ROOT)

    local_nodes = [n for n in nodes if is_local_node(n)]
    external = [n["host"] for n in nodes if not is_local_node(n)]
    if external:
        print(f"  Skipping external nodes (real hostnames): {', '.join(external)}")

    lines = [
        "# AUTO-GENERATED by local/init-nodes.py — do not edit by hand.",
        "# Source: data.local.json   Regenerated on every make init-local / run-local.",
        "services:",
    ]

    node_hosts = []
    for node in local_nodes:
        h = node["host"]
        node_hosts.append(h)
        port = node["port"]
        db = str(db_dir(node))
        certs = str(certs_dir(node))
        lines += [
            "",
            f"  {h}:",
            f"    image: {_q(f'{DEFAULT_IMAGE}:{tag}')}",
            f"    container_name: {_q(f'xui-local-{h}')}",
            f"    hostname: {_q(h)}",
            "    ports:",
            f"      - {_q(f'127.0.0.1:{port}:{port}')}",
            "    volumes:",
            f"      - {_q(f'{db}:/etc/x-ui')}",
            f"      - {_q(f'{certs}:/root/cert:ro')}",
            "    environment:",
            '      XRAY_VMESS_AEAD_FORCED: "false"',
            "    restart: unless-stopped",
        ]

    lines += [
        "",
        "  app:",
        "    build:",
        f"      context: {_q(root)}",
        "      target: app",
        "    container_name: vpn-cp-local",
        f"    env_file: {_q(env_file)}",
        "    environment:",
        "      VPN_DATA_FILE: /app/data/data.local.json",
        "    ports:",
        f"      - {_q(f'127.0.0.1:{http_port}:{http_port}')}",
        "    volumes:",
        f"      - {_q(f'{env_file}:/app/.env:ro')}",
        f"      - {_q(f'{root}:/app/data')}",
        "    depends_on:",
        *[f"      - {h}" for h in node_hosts],
        "    restart: unless-stopped",
    ]

    COMPOSE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {COMPOSE_OUT}  ({len(node_hosts)} local node(s): {', '.join(node_hosts)})")


# ── database operations ───────────────────────────────────────────────────────


def _upsert(con: sqlite3.Connection, key: str, val: str) -> None:
    cur = con.execute("UPDATE settings SET value=? WHERE key=?", (val, key))
    if cur.rowcount == 0:
        con.execute("INSERT INTO settings (key, value) VALUES (?,?)", (key, val))


def patch_db(path: Path, node: dict) -> None:
    """Set apiToken / webPort / webBasePath and clear HTTPS settings."""
    con = sqlite3.connect(path)
    try:
        con.execute(
            "UPDATE settings SET value='' WHERE key IN "
            "('webCertFile','webKeyFile','subCertFile','subKeyFile',"
            " 'webDomain','subDomain','webListen','subListen')"
        )
        _upsert(con, "webPort", str(node["port"]))
        _upsert(con, "webBasePath", node.get("basePath", "/"))
        _upsert(con, "apiToken", node["apiToken"])
        con.commit()
    finally:
        con.close()


def seed_from_backup(node: dict) -> bool:
    """Copy backup.db → x-ui.db if backup exists. Returns True on success."""
    src = backup_db_path(node)
    if not src.exists():
        return False
    dst = db_path(node)
    _drop_wal(dst)
    shutil.copyfile(src, dst)
    print(f"  {node['host']}: seeded from {src.name}")
    return True


def bootstrap_db(node: dict) -> None:
    """Start container so 3x-ui creates the DB schema, then stop it."""
    h = node["host"]
    print(f"  {h}: no DB — bootstrapping (starting container briefly)…")
    base = [
        "docker",
        "compose",
        "-f",
        str(COMPOSE_OUT),
        *(["--env-file", str(ENV_FILE)] if ENV_FILE.exists() else []),
    ]
    subprocess.run([*base, "up", "-d", h], check=True, capture_output=True, text=True)
    db = db_path(node)
    deadline = time.time() + 40
    while not db.exists() and time.time() < deadline:
        time.sleep(1)
    if not db.exists():
        subprocess.run([*base, "stop", h], check=False, capture_output=True)
        raise RuntimeError(f"DB did not appear at {db} (40 s timeout) — is Docker running?")
    time.sleep(1)
    subprocess.run([*base, "stop", h], check=True, capture_output=True, text=True)
    _drop_wal(db)
    print(f"  {h}: DB created")


def init_node(node: dict, *, restore: bool, patch_only: bool) -> None:
    h = node["host"]
    token = node.get("apiToken", "").strip()
    if not token or token.startswith("change-me"):
        print(f"  {h}: [skip] apiToken is a placeholder — fill in data.local.json")
        return

    db_dir(node).mkdir(parents=True, exist_ok=True)
    certs_dir(node).mkdir(parents=True, exist_ok=True)

    db = db_path(node)

    if not db.exists():
        if patch_only:
            raise RuntimeError("DB missing — run: make init-local")
        if not seed_from_backup(node):
            bootstrap_db(node)
    elif restore:
        if not seed_from_backup(node):
            print(f"  {h}: no backup.db found — keeping existing DB")

    if db.exists():
        patch_db(db, node)
        print(f"  {h}: patched ✓")


# ── main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--restore", action="store_true", help="re-seed DBs from backup.db (overwrites existing x-ui.db)")
    ap.add_argument("--patch-only", action="store_true", help="patch existing DBs only; error if any DB is missing")
    args = ap.parse_args()

    load_env_file(ENV_FILE)
    nodes = load_nodes()
    if not nodes:
        return

    generate_compose(nodes)

    mode = "restore" if args.restore else ("patch-only" if args.patch_only else "bootstrap")
    local_nodes = [n for n in nodes if is_local_node(n)]
    print(f"\nInitializing DBs  [{mode}]  ({len(local_nodes)} local node(s))")

    failed = False
    for node in local_nodes:
        print(f"\n--- {node['host']} ---")
        try:
            init_node(node, restore=args.restore, patch_only=args.patch_only)
        except Exception as exc:
            print(f"  [error] {exc}")
            failed = True

    print()
    if failed:
        sys.exit(1)
    if not args.patch_only:
        print("Done. Run: make run-local")


if __name__ == "__main__":
    main()
